steps:
  - name: "node:16.14.2"
    args:
      - "install"
    id: init
    entrypoint: "npm"
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    waitFor:
      - "init"
    entrypoint: "npm"
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    waitFor:
      - "init"
    id: build
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        _VERSION=$(date +%s)
        echo "Deploying version $_VERSION"
        gcloud app deploy --version $_VERSION --quiet
    waitFor:
      - "build"
options:
  logging: CLOUD_LOGGING_ONLY
