steps:
  - name: "node:16.14.2"
    args:
      - "install"
    id: init
    entrypoint: "npm"
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    waitFor:
      - "init"
    entrypoint: "npm"
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    waitFor:
      - "init"
    id: build
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "c"
      - |
        VERSION=$(git rev-parse --short HEAD)
        gcloud app deploy --version $VERSION --quiet
    waitFor:
      - "build"
    entrypoint: "gcloud"
options:
  logging: CLOUD_LOGGING_ONLY
